Dp 46
pepfar-datim/datapackr pull request #265
Opened 2021-03-25 20:11 UTC by maxwellchandler

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Summary of Proposed Changes

## Affected Process Elements
- [ ] Data Pack generation
- [ ] Data Pack model
- [ ] Data Pack self-service app
- [ ] Data Pack processing
- [ ] Site Tool model/distribution
- [ ] Site Tool generation (from Data Pack)
- [ ] Site Tool generation (from DATIM - for OPUs)
- [ ] Site Tool self-service app
- [ ] Site Tool to Data Pack comparison self-service app
- [ ] Site Tool to DATIM comparison self-service app
- [ ] Site Tool processing
- [ ] Site Tool import

## Types of changes

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Related Issues

- Resolves #01
- Fixes #02
- Closes #03

## Testing Approach

## Final Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-03-27 18:58 UTC, sam-bao requested changes

2021-03-27 18:58 UTC, sam-bao commented on R/unPackCountryUIDs.R
> +    psnu_uid = stringr::str_extract(PSNU, "[A-Za-z][A-Za-z0-9]{10}")) %>%
@maxwellchandler I think this change is a problem. The PSNU column has text like `Chiradzulu District   [#SNU] [oiPR2CiVJbf]`. It looks like you would extract the part of a PSNU name if it was 11 characters. e.g.

```
 stringr::str_extract("Chiradzuluu District [#SNU] [oiPR2CiVJbf]", "[A-Za-z][A-Za-z0-9]{10}")
[1] "Chiradzuluu"
```


`

2021-03-27 18:58 UTC, sam-bao commented on tests/testthat/test-signature.R
> +   d <- datapackr:::createKeychainInfo(submission_path = test_sheet('COP20_Data_Pack_Template_v2.xlsx'))
Why did you need to add a new template file? what is different compared to COP20_Data_Pack_Template_vFINAL?

2021-03-27 18:58 UTC, sam-bao commented on tests/testthat/test-signature.R
> +   d <- datapackr:::createKeychainInfo(submission_path = test_sheet('COP20_Data_Pack_Template_v2.xlsx'))
Also it might be best to update these tests to use the COP21 datapack template. https://github.com/pepfar-datim/datapackr/blob/dp-46/inst/extdata/COP21_Data_Pack_Template.xlsx

2021-03-27 18:58 UTC, sam-bao commented on tests/testthat/test-signature.R
> +   }
Why was this code added?

2021-03-29 17:55 UTC, maxwellchandler commented on tests/testthat/test-signature.R
> +   d <- datapackr:::createKeychainInfo(submission_path = test_sheet('COP20_Data_Pack_Template_v2.xlsx'))
@sam-bao The template will not work do to the flaws jason pointed out in the orignal ticket. If there is no data in the prioritization tab then there is nothing to join on later in the code and we get errors. Thus ive taken the original template and have written data to it.

2021-03-29 17:56 UTC, maxwellchandler commented on tests/testthat/test-signature.R
> +   }
@sam-bao This code is showing how the new "template" was created, it overwrites the old file when the tests run and only takes 5 seconds

2021-03-29 18:00 UTC, maxwellchandler commented on tests/testthat/test-signature.R
> +   }
@sam-bao I was able to fix one of the adorn mechanisms test but I simply cannot get the first part to work. So I commented it out.  I know that @jason-p-pickering was originally intending testing for a warning message but I cant get a warning message to produce.

2021-04-06 05:01 UTC, sam-bao commented on tests/testthat/test-adorn-mechanisms.R
> +#   })
@jason-p-pickering it looks like this warning was made obsolete in this commit: https://github.com/pepfar-datim/datapackr/pull/259/files#diff-7324252ebfd88f96094818c81ac4dfae619cd15b6e0d062839b1f4ef124a3388L187

Can we get rid of this test?

2021-04-06 07:29 UTC, sam-bao commented on tests/testthat/test-signature.R
> +   }
@maxwellchandler we do not currently have xlsx package as a dependency. I am reluctant to add this dependency just for testing purposes. Is there a reason you cannot use openxlsx?

I am getting the following errors which are at least partially explained by the fact that I do not have the xlsx package installed.

```
> setwd("~/Documents/GitHub/datapackr")
> devtools::test()
Loading datapackr
Testing datapackr
✓ |  OK F W S | Context
✓ |   3       | Test GetDataValueSets [0.6 s]                                                                 
✓ |   3       | Get a mechanism view when logged into DATIM [3.5 s]                                           
x                                                                                                           - |   1 1 1   | test-get-datapack-name                                                                        - |   1 1     | test-get-datapack-name                                                                        
──────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test-get-datapack-name.R:22:3): Can read a Datapack Name and UIDs
Error: Deduced or provided Country UIDs do no match Country UIDs observed in submission.
Backtrace:
 1. datapackr:::unPackCountryUIDs(...) test-get-datapack-name.R:22:2

Warning (test-get-datapack-name.R:38:3): Can error on an invalid regional DataPack UID
Unable to deduce Country UIDs from cell B25 on Home tab. Attempting to deduce from org units listed on Prioritization tab instead.
Backtrace:
 1. testthat::expect_error(datapackr:::unPackCountryUIDs(submission_path = template_copy)) test-get-datapack-name.R:38:2
 6. datapackr:::unPackCountryUIDs(submission_path = template_copy)

Warning (test-get-datapack-name.R:38:3): Can error on an invalid regional DataPack UID
Unable to deduce Country UIDs from Prioritization tab. Attempting to deduce from Data Pack name on Home tab.
Backtrace:
 1. testthat::expect_error(datapackr:::unPackCountryUIDs(submission_path = template_copy)) test-get-datapack-name.R:38:2
 6. datapackr:::unPackCountryUIDs(submission_path = template_copy)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────
✓ |   2       | test-handshake                                                                                
✓ |  18       | dedupe [0.4 s]                                                                                
✓ |   9       | rounding                                                                                      
x |   0 2     | test-signature [0.2 s]                                                                        
──────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test-signature.R:4:4): Can generate a signature
Error: there is no package called 'xlsx'
Backtrace:
 1. xlsx::loadWorkbook test-signature.R:4:3
 2. base::getExportedValue(pkg, name)
 3. base::asNamespace(ns)
 4. base::getNamespace(ns)
 5. base::loadNamespace(name)
 6. base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 7. base:::withOneRestart(expr, restarts[[1L]])
 8. base:::doWithOneRestart(return(expr), restart)

Error (test-signature.R:49:4): Can get the type and COP year of tool of a COP20 Data Pack
Error: Deduced or provided Country UIDs do no match Country UIDs observed in submission.
Backtrace:
 1. datapackr:::createKeychainInfo(submission_path = test_sheet("COP20_Data_Pack_Template_v2.xlsx")) test-signature.R:49:3
 2. datapackr::unPackCountryUIDs(...) /Users/sam/Documents/GitHub/datapackr/R/createKeychainInfo.R:142:4
──────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 21.3 s

[ FAIL 3 | WARN 2 | SKIP 0 | PASS 37 ]
```

2021-04-06 19:46 UTC, maxwellchandler commented on tests/testthat/test-signature.R
> +   }
using open xlsx is not possible. It saves corrupted files
https://github.com/awalker89/openxlsx/issues/22

2021-04-06 19:50 UTC, maxwellchandler commented on tests/testthat/test-signature.R
> +   }
@sam-bao If you really do not want xlsx as a dependency we can just remove the code that makes it and use only the file

2021-04-06 20:38 UTC, maxwellchandler commented on tests/testthat/test-signature.R
> +   }
openxlsx also hasnt seen development in over 3 years now, its dead code in my opinion. I highly reccomend we switch to xlsx for everything, its far more robust.

2021-04-06 21:09 UTC, maxwellchandler commented
@sam-bao After the new changes yoy should be getting all tests passed without the need to install xlsx

2021-07-14 14:13 UTC, closed without merging

2021-07-14 14:13 UTC, sam-bao commented
Fixed in another committ

https://github.com/pepfar-datim/datapackr/commit/acf4ae251572fea8f82aa0774d13d76e2d564c22