Update and create functions for producing test datasets from datapackr
pepfar-datim/datapackr pull request #286
Opened 2021-04-29 22:25 UTC by jacksonsj

Contains two functions to allow production of test data:
- createTestDataset produces a test dataset for a given country that crosses all possible PSNUs, mechs, DEs, and COCs.
- createTestDataset.holistic takes a more nuanced approach, producing a list object with various test datasets each aimed at testing a specific data management assumption involved in COP.

2021-04-30 05:50 UTC, jason-p-pickering requested changes
In general I am OK with this,but please consider the code style changes which I have suggested before merging.

2021-04-30 05:50 UTC, jason-p-pickering commented on NAMESPACE
> +export(createTestDataset.holistic)
Could we avoid the use of "." in function names? This is really just more of a code style issue I think. 

Perhaps we could have `createTestDataSet(....,type="holistic")` as a wrapper to various types of test datasets?

2021-04-30 05:50 UTC, jason-p-pickering commented on R/createTestDataset.holistic.R
> +  #TODO: Functionalize repetitive code above
Yes, I would agree with this. Should be fairly simple ?

2022-01-31 14:57 UTC, cnemarich commented
Too far out of sync with `dev`. Cherry-picked relevant commits on `update-createTestDataset-repair`. Please refer back to these notes from @jason-p-pickering on suggested updates.

2022-01-31 14:57 UTC, closed without merging