Unit testing redux
pepfar-datim/datapackr pull request #292
Opened 2021-05-19 09:45 UTC by jason-p-pickering

- Add new unit tests
- Fix some unit tests
- Skip some unit tests

2021-06-16 12:53 UTC, sam-bao requested changes
@jason-p-pickering I have done a code review of the non-test changes. I have a couple of comments and one change suggestion.

I will continue to review the actual tests tomorrow. I was able to run the test suite without issue, but will also do a code review of each test.

2021-06-16 12:53 UTC, sam-bao commented on R/packSNUxIM.R
> +               +1)),
What are these changes about? Did scott pull out these changes directly in this unit testing branch: https://github.com/pepfar-datim/datapackr/commit/56d9409092d11df74a53d595f1d3a7469acec916?

2021-06-21 06:41 UTC, jason-p-pickering commented on R/createKeychainInfo.R
> +  if (d$info$tool %in% c("Data Pack", "Data Pack Template", "OPU Data Pack", "OPU Data Pack Template")
@sam-bao I would agree that it would seem to be need to be set unconditionally. @jacksonsj you made this change as part of https://github.com/pepfar-datim/datapackr/compare/issues/dp250. Do you want to have another look?

2021-06-21 06:45 UTC, jason-p-pickering commented on R/getDataValueSets.R
> +                                            lastupdated = "T")) %>%
Yeah, that is fine. I put that warning suppression back in.

2021-06-21 07:07 UTC, jason-p-pickering commented on R/packSNUxIM.R
> +               +1)),
@jacksonsj could you double check? As far as I know this turns off the dragging of column formulas down on the right side of the PSNUxIM tab. The code seems to match https://github.com/pepfar-datim/datapackr/commit/56d9409092d11df74a53d595f1d3a7469acec916

2021-06-29 07:15 UTC, jason-p-pickering commented on R/packSNUxIM.R
> +               +1)),
@jacksonsj bumping this for your comment.

2021-07-06 14:51 UTC, jacksonsj commented on R/packSNUxIM.R
> +               +1)),
Yes that’s right. This change turns off the automatic formula dragging down on the right side of the PSNUxIM tab. @jason-p-pickering @sam-bao

2021-07-06 14:54 UTC, jacksonsj commented on R/createKeychainInfo.R
> +  if (d$info$tool %in% c("Data Pack", "Data Pack Template", "OPU Data Pack", "OPU Data Pack Template")
I think I lean toward there being a standard schema of flags/tags for both OPU and COP Data Packs to make it easier to interchange and handle these across all our various places. I can take another look to do that, but that can also happen separate from this specific PR too. @jason-p-pickering @sam-bao - would you prefer that as part of this PR, or separate?

2021-07-13 11:09 UTC, sam-bao requested changes

2021-07-13 11:09 UTC, sam-bao commented on tests/testthat/test-adorn-mechanisms.R
> +      skip("Need to simulate a dead handle.")
We can leave this as a skipped test and resolve individually in a branch off of dev before this goes into master, but I don't think ideally we should make this test functional before merging into master.

2021-07-14 10:15 UTC, sam-bao approved these changes
There are still some outstanding comments on this PR, but they needn't block merging into dev.

2021-07-14 10:15 UTC, merged