Issues/dp 281
pepfar-datim/datapackr pull request #302
Opened 2021-08-17 05:18 UTC by jacksonsj

2021-08-17 05:26 UTC, jacksonsj commented
@sam-bao - Would you mind giving this a quick review before we pull into `dev`? We'll do a subsequent, more comprehensive review here soon of `dev` -> `master`.

2021-08-17 05:29 UTC, jacksonsj commented on R/adorn_import_file.R
> +  if (filter_rename_output) {
@sam-bao - This change uses a parameter to allow the default to remain as it was for all existing functions that used this, but adds an option I use for COP21 OPU creation to keep all columns in the output and filter more selectively within a downstream function.

2021-08-17 05:31 UTC, jacksonsj commented on R/create_play_spectrum_output.R
> +                tool = "Spectrum Example",
@sam-bao - As part of this branch, I reviewed some of the parameters used across OPU generation and saw that we use `type` and `tool` interchangeably, but also use `type` as a parameter in other functions though referring to something entirely different from whether a COP or OPU Data Pack. So I standardize the parameter names we use across these functions to use only `tool` to describe whether a process is producing/validating a COP or OPU Data Pack.

2021-08-17 05:33 UTC, jacksonsj commented on R/getOPUDataFromDATIM.R
> +  # COP21+: Output as DHIS2 import file ####
@sam-bao - This keeps the output identical for existing functions, but for COP21 OPU Data Packs, produces the output as a DHIS2 import file. We could also structure this to use a parameter option instead — e.g., `import_structure = TRUE` turns on this feature, but the default is `= FALSE` to allow backward compatibility with all the places using this function already.

2021-08-17 05:36 UTC, jacksonsj commented on R/packPSNUxIM.R
> +packPSNUxIM <- function(wb,
@sam-bao - This function will eventually entirely replace all the various ones we had before for packing the differently structure PSNUxIM tabs we had between COP and OPU and 2019 and 2020 and 2021. For now, I've set this up to only work for COP21 OPU Data Pack PSNUxIM tabs, but most of the code comes from the `packSNUxIM` function we used for COP21 Data Pack PSNUxIM tabs, anticipating eventually using this one function to write either COP or OPU PSNUxIM tabs.

2021-08-17 05:37 UTC, jacksonsj commented on R/packSNUxIM_OPU.R
> +  if (NROW(d$data$snuxim_model_data) == 0) {
@sam-bao - Just standardizing here and elsewhere how we refer to the SNUxIM model data, to distinguish from the Data Pack Model Data we use in first populating COP Data Packs

2021-08-17 05:41 UTC, jacksonsj commented on R/packageSetup.R
> +datapackr_params <- function(model_data,
@sam-bao - Eventually, we can use this function and @inheritParams in `roxygyen` to keep just one central, standardized list of parameter definitions we can then reference in other functions where we want to. Again, this came up as an idea after reviewing our functions and realizing how disjointed our use of parameter names and meanings was across the package.

2021-08-17 05:43 UTC, jacksonsj commented on R/packageSetup.R
> +check_params <- function(country_uids,
@sam-bao - This can grow with our package and for now only really covers usage within the OPU Data Pack realm, but the idea is to standardize how we validate supplied parameters and fill in unsupplied/`NULL` ones.

2021-08-17 05:45 UTC, jacksonsj commented on R/utilities.R
> +createWorkbook <- function(datapack_name = NULL,
@sam-bao - This is part of the process of standardizing how we fill in unsupplied/`NULL` parameters, so if we wanted to pull a function out and run it more independently, we could quick create a shell Workbook based on the supplied COP Year and tool type to then use within a function that needs a Workbook.

2021-08-17 05:46 UTC, jacksonsj commented on R/packOPUDataPack.R
> +#' @inheritParams datapackr_params
@sam-bao - See comment in `packageSetup`

2021-08-17 05:48 UTC, jacksonsj commented on R/packOPUDataPack.R
> +  if (d$info$cop_year == 2021) {
@sam-bao - For COP21 OPU Data Packs, we'll need to separate and `summarise` the target totals and use these within `packPSNUxIM`, rather than using a function to pull these targets from other tabs in the Data Pack. This is part of trying to design `packPSNUxIM` to be compatible with both COP and OPU PSNUxIM tabs.

2021-08-17 05:51 UTC, jacksonsj commented on R/packOPUDataPack.R
> +      r <- packPSNUxIM(wb = d$tool$wb,
I've written `packPSNUxIM` to return a small list object called `r` that has only two components: the final workbook with populated PSNUxIM tab, and any messages. This same method could be used across the package for other functions to move away from monolithic and opaque usage of the `d` object where it's unclear for any given function what that needs to include, to supplying these pieces more explicitly as parameters and returning both the outputs and messages as a separate list object to then be reassigned into `d` as needed. This should also help with testability and modularization.

2021-08-17 08:04 UTC, jason-p-pickering commented on R/packOPUDataPack.R
> -                type = d$info$type,
Seems to be some confusion here as to whether use `tool` or `type`. If we change this from d$info$tool to d$info$type, that is going to be a breaking change with the self-service app. We can of course change it there, but is this really a necessary change?

2021-08-17 08:04 UTC, jason-p-pickering requested changes
Please see my comment below regarding the change and/or confusion around d$info$tool.

2021-08-18 12:25 UTC, sam-bao commented on R/packageSetup.R
> +pick_schema <- function(cop_year = getCurrentCOPYear(), tool = "Data Pack") {
@jacksonsj this partially overlaps with this function: https://github.com/pepfar-datim/datapackr/blob/ed4f0a0bddecc430b9fa84230a24f08c109fef3c/R/utilities.R#L530. 

Should we consolidate and update the code which utilizes getDataPackSchema

2021-08-18 12:44 UTC, sam-bao commented on R/packageSetup.R
> +pick_schema <- function(cop_year = getCurrentCOPYear(), tool = "Data Pack") {
Unless there is a reason for us to call this function regularly from the commandline I don't think it should have a default cop_year. It should receive cop_year explicitly from a higher level function like packOPUDataPack which may have a default cop_year. The risk is that we write a higher level function which uses this function, we forget to explicitly pass cop_year when that higher level function calls `pick_schema` and then it uses a default schema for the current cop year which could be inconsistent with the higher level function. So leaving the default for cop_year off of these utility functions is more defensive programming.

2021-08-19 22:17 UTC, jacksonsj commented on R/packageSetup.R
> +pick_schema <- function(cop_year = getCurrentCOPYear(), tool = "Data Pack") {
Agreed. I'll change.

2021-08-20 05:17 UTC, jacksonsj commented on R/packageSetup.R
> +pick_schema <- function(cop_year = getCurrentCOPYear(), tool = "Data Pack") {
@sam-bao - I've addressed this here: https://github.com/pepfar-datim/datapackr/pull/302/commits/8b2733cdc7bbe78c4af0e25d8e8af53eacf93bb5

2021-08-20 05:18 UTC, jacksonsj commented on R/packOPUDataPack.R
> -                type = d$info$type,
Debatable, for sure. I think overall, we definitely have issues with lack of consistency around our use of parameter names and definitions. We'll need to solve that at some point.

2021-08-20 10:47 UTC, sam-bao commented on R/packageSetup.R
> +pick_schema <- function(cop_year = getCurrentCOPYear(), tool = "Data Pack") {
@jacksonsj we still have the redundant function `pick_schema` and `getDataPackSchema`. I would probably just convert pick_schema to getOPUDataPackSchema(cop_year)

2021-08-23 05:30 UTC, jason-p-pickering commented on R/packageSetup.R
> +pick_schema <- function(cop_year = getCurrentCOPYear(), tool = "Data Pack") {
Or maybe just `getSchema(tool = "OPU Data Pack", cop_year=2021)`. I am not totally sure why we need to distinguish in the function name? It would seem that both an OPU and DataPack have a schema and we just need to tell the function which type of tool we are dealing with?

2021-08-23 06:23 UTC, jason-p-pickering commented on R/checkNumericValues.R
> +        " FY22 Target columns include numeric values only - no letters or punctuation.",
BTW @sam-bao and @jacksonsj , the em-dash (long) is a non ASCII character, and the package checks complained about this. This was the reason for this change.

2021-08-23 12:52 UTC, sam-bao commented on R/handshakeFile.R
> +                          tool = "Data Pack") {
@jacksonsj I don't see why this needs a default value. Shouldn't we be explicit in the tool we are getting?

2021-08-23 12:59 UTC, sam-bao commented on R/packDataPack.R
> +  if (d$info$cop_year == 2020) {
@jacksonsj doesn't the pick_schema funtion do this?

2021-08-23 13:03 UTC, jason-p-pickering commented on R/packageSetup.R
> +datapackr_params <- function(model_data,
When writing tests, I came across this function. It is odd in that it does nothing but return NULL, which itself is not explicitly declared. This is generally not good practice. I think the better approach would be to have this function return the list of formal arguments as a list, which we can then use as a test for the other functions which you have created. 

so, if it datapackr_params returned `rlang::fn_fmls_names(fn = datapackr_params)` then we know exactly which arguments are being called (well at least their names) and can then test the other functions which you have implemented using this constructor. 

Thoughts @sam-bao @jacksonsj ?

2021-08-23 14:41 UTC, sam-bao commented on R/prepare_model_data.PSNUxIM.R
> +  if (inherits(snuxim_model_data, "list")) {
@jacksonsj I don't really understand what this if statement is for, can you explain what is going on here?

2021-08-23 14:43 UTC, sam-bao commented on R/prepare_model_data.PSNUxIM.R
> +    dplyr::filter(stringr::str_detect(mechanism_code, "\\d{4,}"),
@jacksonsj just so I am clear - is this mainly to drop DREAMS data at the moment?

2021-08-23 14:46 UTC, sam-bao commented on R/prepare_model_data.PSNUxIM.R
> +      `Total Duplicated Rollup` = rowSums(dplyr::select(., tidyselect::matches("\\d{4,}|HllvX50cXC0")), na.rm = TRUE),
@jacksonsj If we drop dreams data, is the default mechanism supposed to be listed here?

2021-08-23 15:11 UTC, sam-bao commented on R/packageSetup.R
> +check_params <- function(country_uids,
@jacksonsj a bit confused, there are a number of functions nested in this function but then they aren't actually called. Is this functional? If not I say we pull this into a separate feature branch. I think this needs unit tests before it is merged as well.

2021-08-23 15:14 UTC, sam-bao commented on R/packageSetup.R
> +  }
@jacksonsj what if not 2020 or 2021?

2021-08-23 15:19 UTC, sam-bao commented on R/packageSetup.R
> +    } else {schema <- datapackr::data_pack_schema}
Not sure I like that if I give a cop year of 2022 right now that I get the cop21 schema. In theory we shouldn't call this with 2022 until there is a COP22 schema - but new team members might be confused. In fact I think the cop22 schema should start its life as the cop22 schema not as the data_pack_schema.

2021-08-23 15:24 UTC, jason-p-pickering commented on R/packageSetup.R
> +check_params <- function(country_uids,
I started with a few unit tests, and agree, that we need tests here. I do not see a compelling reason to have these functions nested. I think they can simply not be exported, if they are part of something bigger, but as separate functions, it makes them much easier to individually test. See some of my tests in 4eb5d224f03979ce8d383aa8b7c8c8f4dd5840e4, which I think could be extended to provide more coverage.

2021-08-23 15:28 UTC, jason-p-pickering commented on R/prepare_model_data.PSNUxIM.R
> +  if (inherits(snuxim_model_data, "list")) {
For me the bigger question here is what happens when its not a list or its a list but with the wrong structure. I think it would be better to be explicit and be sure that whatever is being passed via the `snuxim_model_data` is what we actually expect it is and not simply a list.

2021-08-23 17:01 UTC, sam-bao commented on R/packOPUDataPack.R
> +        dplyr::summarise(value = sum(value)) %>%
@jacksonsj any chance for `NA` here? If so the sum will be `NA` unles we set na.rm=TRUE

2021-08-24 07:02 UTC, jason-p-pickering commented on R/packageSetup.R
> +    } else {schema <- datapackr::data_pack_schema}
See my comment in the tests, where this did not feel entirely right to me. 

```
  #Are we sure we want to return this object for anything other than 2020 
  # and 2021?
  test_schema<-pick_schema(1999,"Data Pack") 
  testthat::expect_identical(test_schema,  datapackr::data_pack_schema)

2021-08-24 08:44 UTC, sam-bao commented on R/packOPUDataPack.R
> +      dplyr::filter(rowSums(is.na(.)) != ncol(.))
@jacksonsj  I had trouble understanding the logic here. @jason-p-pickering helped me unpack it, and he suggested this as perhaps a more straightforward check.

`all(is.na(bar))`

Jason's suggestion seems easier to understand if the intent is to check for a dataframe with all NA.

2021-08-24 12:05 UTC, sam-bao commented on NAMESPACE
> +export(check_params)
@jacksonsj Shouldn't this be called `checkParams`? There are other examples of function names here that diverge from camelCase as well

2021-08-24 12:32 UTC, sam-bao commented on R/packageSetup.R
> +check_params <- function(country_uids,
I am also looking at the usage of check_params in packPSNUxIM, and I now see the thinking is that this will not just check the validity of parameters but also transform them and pass them back to the calling function. I am not sure letting check_params alter the value of parameters is a good thing. Especially when it is happening in a function like `packPSNUxIM` which we will not call directly. parameters set in a higher level function shouldn't have the chance to get altered in internal function like `packPSNUxIM`. 

Also to reiterate a point I think I made before, I don't think we should be exporting every function in the package. Other than for development and testing `packPSNUxIM` will only be called by another `datapackr` function. So if there was a need to transform a parameter it should have happened before that parameter got to packPSNUxIM.

To refocus on the issue at hand here, I am really nervous that check_params is potential altering values of parameters in low level functions, and even in higher level functions may cause confusion.

2021-08-24 13:03 UTC, jacksonsj commented on R/packageSetup.R
> +pick_schema <- function(cop_year = getCurrentCOPYear(), tool = "Data Pack") {
I'll create a ticket for consolidating, but would like to handle in a separate PR: https://jira.pepfar.net/browse/DP-289

2021-08-24 13:17 UTC, jacksonsj commented on R/handshakeFile.R
> +                          tool = "Data Pack") {
I'll create a ticket to analyze and standardize how we handle parameter defaults across the package: https://jira.pepfar.net/browse/DP-290

2021-08-24 13:19 UTC, jacksonsj commented on NAMESPACE
> +export(check_params)
Documenting and will resolve via: https://jira.pepfar.net/browse/DP-291

2021-08-24 13:20 UTC, jacksonsj commented on R/packageSetup.R
> +check_params <- function(country_uids,
Will resolve via: https://jira.pepfar.net/browse/DP-290

2021-08-24 13:22 UTC, sam-bao commented on R/prepare_model_data.PSNUxIM.R
> +  if (inherits(snuxim_model_data, "list")) {
can we us `is.list()`?

2021-08-24 13:23 UTC, sam-bao commented on R/prepare_model_data.PSNUxIM.R
> +  if (inherits(snuxim_model_data, "list")) {
or `typeof`

2021-08-24 13:26 UTC, jacksonsj commented on R/prepare_model_data.PSNUxIM.R
> +    dplyr::filter(stringr::str_detect(mechanism_code, "\\d{4,}"),
Yes, but rather than explicitly drop `AGYW_PREV`, I've generalized.

2021-08-24 13:26 UTC, jacksonsj commented on R/prepare_model_data.PSNUxIM.R
> +      `Total Duplicated Rollup` = rowSums(dplyr::select(., tidyselect::matches("\\d{4,}|HllvX50cXC0")), na.rm = TRUE),
Yes, probably could remove.

2021-08-24 13:27 UTC, sam-bao commented on R/prepare_model_data.PSNUxIM.R
> +      `Total Duplicated Rollup` = rowSums(dplyr::select(., tidyselect::matches("\\d{4,}|HllvX50cXC0")), na.rm = TRUE),
Probably redundant, @sam-bao to double check and remove.

2021-08-24 13:27 UTC, jacksonsj commented on R/prepare_model_data.PSNUxIM.R
> +  if (inherits(snuxim_model_data, "list")) {
I'll review and see if we can make this more explicit.

2021-08-24 13:30 UTC, jacksonsj commented on R/packageSetup.R
> +  }
Will resolve this here: https://jira.pepfar.net/browse/DP-292

2021-08-24 13:31 UTC, jacksonsj commented on R/packageSetup.R
> +    } else {schema <- datapackr::data_pack_schema}
Will resolve this here: https://jira.pepfar.net/browse/DP-292

2021-08-24 13:33 UTC, jacksonsj commented on R/packOPUDataPack.R
> +      dplyr::filter(rowSums(is.na(.)) != ncol(.))
I'll look at this and try to resolve in this PR.

2021-08-24 13:35 UTC, jacksonsj commented on R/packOPUDataPack.R
> -                type = d$info$type,
In other words, yes, this needs to remain, and we'll have to update the SSA code.

2021-08-24 13:39 UTC, jacksonsj commented on R/packDataPack.R
> +  if (d$info$cop_year == 2020) {
Yes, but I felt like changing that here was out of scope for this PR since this is focused on OPU generation, not COP generation. I'll create a new ticket for this and resolve in a separate PR.

https://jira.pepfar.net/browse/DP-294

2021-08-24 13:41 UTC, jacksonsj commented on R/utilities.R
> +createWorkbook <- function(datapack_name = NULL,
Noting here that I'll need to change this function name to deconflict with `openxlsx`: https://jira.pepfar.net/browse/DP-295

2021-08-25 12:24 UTC, sam-bao approved these changes
@jacksonsj I am done with QA. I think there were a few minor changes you wanted to add to this PR, so rather than merging I am marking as approved for you to merge when you are done.

Should we increment to version 5.0.0? There are some breaking changes so that would seem appropriate.

2021-09-23 03:20 UTC, merged