Issues/dp 287 into issues/dp 281
pepfar-datim/datapackr pull request #305
Opened 2021-08-23 06:13 UTC by jason-p-pickering

Redoing this PR to make it more clear what has changed. Instead of dp-287 going directly into dev, this one is comparing against dp-281.

2021-09-06 20:00 UTC, sam-bao requested changes

2021-09-11 20:51 UTC, jacksonsj commented on R/packageSetup.R
> +      return(datapackr::data_pack_schema)
Capturing this here for a new PR: https://jira.pepfar.net/browse/DP-292

2021-09-11 20:52 UTC, jacksonsj commented on tests/testthat/test-package-setup.R
> +  test_schema<-pick_schema(1999,"Data Pack")
Capturing here to address in a new PR: https://jira.pepfar.net/browse/DP-292

2021-09-11 20:53 UTC, jacksonsj commented on R/createKeychainInfo.R
> +    } else if (d$info$cop_year == 2021) {
Yes, will address in a new PR, described here: https://jira.pepfar.net/browse/DP-294

2021-09-11 21:04 UTC, jacksonsj approved these changes

2021-09-11 21:04 UTC, jacksonsj commented on tests/testthat/test-package-setup.R
> +  expect_equal(length(check_params(country_uids = "foo")$country_uids),0L)
Yes, running `check_params()` with no parameters, returns an empty list.

2021-09-11 21:04 UTC, jacksonsj commented on tests/testthat/test-package-setup.R
> +  #Are we sure about this?
For now, yes. We need to review and consolidate our approach to default parameters across the board.

2021-09-11 21:05 UTC, merged