Message refactor
pepfar-datim/datapackr pull request #308
Opened 2021-09-01 12:48 UTC by jason-p-pickering

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Summary of Proposed Changes
- Refactor of message queue to use a simple R6 object instead of a list

## Affected Process Elements
- [ ] Data Pack generation
- [ ] Data Pack model
- [ ] Data Pack self-service app
- [ ] Data Pack processing
- [ ] Site Tool model/distribution
- [ ] Site Tool generation (from Data Pack)
- [ ] Site Tool generation (from DATIM - for OPUs)
- [ ] Site Tool self-service app
- [ ] Site Tool to Data Pack comparison self-service app
- [ ] Site Tool to DATIM comparison self-service app
- [ ] Site Tool processing
- [ ] Site Tool import

## Types of changes

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Does this introduce a breaking change?

- [X] Yes
- [ ] No

This will break the self-service apps for sure, but should be easy to rectify this later. 

## Testing Approach

## Final Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-09-12 02:17 UTC, jacksonsj requested changes

2021-09-12 02:17 UTC, jacksonsj commented on R/messageQueue.R
> +appendMessage.MessageQueue<-function(x, message=NA,level=NA) {
Should any of these here be exported, or at least declared as package functions for reference?

2021-09-12 02:17 UTC, jacksonsj commented on R/messageQueue.R
> +}
Has this been `lintr`ed yet?

2021-09-12 02:17 UTC, jacksonsj commented on R/packPSNUxIM.R
Not sure I understand how this change works. Should this be `appendMessage` instead of `append`?

2021-09-12 02:17 UTC, jacksonsj commented on R/unPackOPU_PSNUxIM.R
> +    d$info$has_error<-TRUE
Instead, could we trigger this `has_error` flag automatically at the end just by the presence of a message with the `"ERROR"` level?

2021-09-15 08:07 UTC, jason-p-pickering commented on R/messageQueue.R
> +appendMessage.MessageQueue<-function(x, message=NA,level=NA) {
I have exported the `printMessages` method. I think that is really the only one which needs to be exposed.

2021-09-15 08:07 UTC, jason-p-pickering commented on R/messageQueue.R
> +}
Not sure what you mean, but yes. :-D

2021-09-15 09:12 UTC, jason-p-pickering commented on R/packPSNUxIM.R
Good catch. I had done a search/replace on `d$info$messages` but this object was structured slightly differently for some reason. I made two changes [here](https://github.com/pepfar-datim/datapackr/blob/d1adb81a88b413739b85e3bfcd542850c180d538/R/packPSNUxIM.R#L42) and [here](https://github.com/pepfar-datim/datapackr/blob/d1adb81a88b413739b85e3bfcd542850c180d538/R/packPSNUxIM.R#L599). This method seems a bit odd to me. Since it kind of constructs a `d` like object, but did not have the same structure. I moved things around a bit to make it more standard, but we might need to take a look at this in more depth to be sure I did not break anything unintentionally.

2021-09-15 09:13 UTC, jason-p-pickering commented on R/unPackOPU_PSNUxIM.R
> +    d$info$has_error<-TRUE
Yes, I had considered doing this. It should be pretty easy to implement, but would suggest we perform another refactor after all of this is merged.

2021-09-23 01:31 UTC, jacksonsj commented on R/checkColStructure.R
> +    purrr::when(sheet == "PSNUxIM" ~ dplyr::filter(., !stringr::str_detect(indicator_code, "\\d{4,}_(DSD|TA)|^$")),
Bravo. Didn't know this existed.

2021-09-23 02:07 UTC, jacksonsj approved these changes

2021-09-23 02:07 UTC, merged