Betaset data
pepfar-datim/datapackr pull request #340
Opened 2021-11-18 01:04 UTC by jacksonsj

## Developer:

### Summary of Proposed Changes

- Adds execution script to produce test Datasets for use in COP22 testing.

### Related Issues
- DP-354

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2021-11-18 23:25 UTC, jacksonsj commented on R/prepareSheetData.R
> -      replacement = as.character(seq_along(NROW(row_headers))
For some reason, this was causing all the formulas to repeat identically, rather than sequence along each row, so I reverted this one line.

2021-11-18 23:31 UTC, jacksonsj commented on R/pullFullCodeList.R
> +  datasets <- datasets %missing% NULL
This is the cause of the 1 failed test. It'll be fixed with that other PR, and adding this one function here would cause an annoying conflict. So, leaving this as is for now.

2021-11-18 23:32 UTC, jacksonsj commented on R/pullFullCodeList.R
> +  datasets <- unique(datasets)
All these changes basically just make this function more flexibly, to allow you to pass a list of datasets to grab instead of the whole custom selection thing that was there before (which still works if you want to use it).

2021-11-18 23:34 UTC, jacksonsj commented on R/pullHTSModality.R
> +          stringr::str_remove_all(hts_modality, fy_pattern)))
This and the fy_pattern update above are to accommodate how some of the newer groupSet names are named slightly differently. This pattern + str_remove_all catches all the varieties.

2021-11-18 23:35 UTC, jacksonsj commented on R/pullHTSModality.R
> +    "2022" = "a0oGIk4aN23",
New groupSet created by Kyle for capturing the SNS modality

2021-11-19 06:20 UTC, jason-p-pickering requested changes
I will fix the linting, but please have look at my other comments before merging.

2021-11-19 06:20 UTC, jason-p-pickering commented on R/pullFullCodeList.R
> +  datasets <- unique(datasets)
Feels repetitive. Can we simplify with `do.call`?

2021-11-19 06:20 UTC, jason-p-pickering commented on R/pullFullCodeList.R
> +  datasets <- datasets %missing% NULL
Once again, I am left scratching my head with the use of `%missing%` instead of just specifying `datasets=NULL` in the default paramaters?

2021-11-19 06:20 UTC, jason-p-pickering commented on R/packDataPack.R
> +                         output_folder,
I think this needs some default parameter? We also need to check that the directory exists, and that we can write to it. If that condition is not met, then we should error out. 

Perhaps set the default to NULL and then 

```
  if ( is.null(output_folder) || file.access(output_folder,2) != 0 ) {
    stop("Cannot write to output_folder")
  }
```

2021-11-19 06:20 UTC, jason-p-pickering commented on R/packageSetup.R
>        stop("Sorry, datapackr only supports COP20 and COP21 Data Packs.")
This comment should be updated I think.

2021-11-19 06:20 UTC, jason-p-pickering commented on R/prepareSheetData.R
> -      replacement = as.character(seq_along(NROW(row_headers))
It should be `seq_len(NROW(row_headers))`

2021-11-19 06:48 UTC, jason-p-pickering commented
@jacksonsj unit tests are still failing due to the lack of availability of `%missing%`

2021-11-29 22:57 UTC, jacksonsj commented on R/packageSetup.R
>        stop("Sorry, datapackr only supports COP20 and COP21 Data Packs.")
I've handled this in that other branch with full check_params implementation

2021-11-29 23:02 UTC, jacksonsj commented on R/pullFullCodeList.R
> +  datasets <- unique(datasets)
Yes, but I'd rather do that in a separate PR focused just on that set of functions.

2021-11-29 23:03 UTC, merged