DP-504: Incorporate non-memo functionality from app into package
pepfar-datim/datapackr pull request #378
Opened 2022-01-31 21:36 UTC by cnemarich

## Developer:

### Summary of Proposed Changes
- Adds `source_user`, `sane_name`, `organisation_unit`, and `uuid` as metadata included in keychain.
    - Adds `d2_session` as an optional argument for the `createKeychainInfo` function to facilitate the creation of the `source_user` metadata.
- Adds `cached_mechs_path` as a standard parameter contained in the `datapackr_params` function.
- Adds the following new functions to the package:
    - `checkMechanisms`, which checks that all mechanisms contained in the PSNUxIM tab are valid for the given COP year. This is based on the function `validateMechanisms` that was in `datapackr-app`.
    - `checkPSNUs`, which checks that all PSNUs contained in the Data Pack tool are contained within DATIM and match with the OU for the tool. This is based on the function `validatePSNUs` that was in `datapackr-app`.
    - `getOUFromCountryUIDs`, which fetches the parent OU name and UID for a tool. For single-country OUs, this simply returns the name and UID of the country, while for regional OUs, this function returns the name and UID of the parent region (e.g. Western Hemisphere). This is based on the function `getOrganisationUnitFromCountryUIDs` that was in `datapackr-app`.
    - `getSaneName` which takes a Data Pack tool name and generates a "Sane name" for the tool which has no spaces or punctuation.

### Related Issues
- DP-504

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2022-02-03 14:07 UTC, jason-p-pickering commented on R/checkPSNUData.R
> +                              paste0(Sys.getenv("support_files_directory"), "cop_validation_rules.rds"),
Perhaps we should include the RDS of the validation rules in the package?

2022-02-03 14:14 UTC, jason-p-pickering commented on DESCRIPTION
> +    waldo,
Are we sure this only needs to be a suggestion? Seems to be called only in `validateSchema`. Fine to leave it as a suggestion if never called by users.

2022-02-03 14:15 UTC, jason-p-pickering commented on R/checkMechanisms.R
> +  operating_unit <- getOperatingUnitFromCountryUIDs(d$info$country_uids)
Don't we already the Operating Unit UID? If not, we should maybe take care of this when getting country UIDs?

2022-02-03 14:16 UTC, jason-p-pickering commented on R/checkMechanisms.R
> +    d$info$had_error <- TRUE
I think this should be `has_error`

2022-02-03 14:18 UTC, jason-p-pickering commented on R/checkPSNUData.R
> +  # TODO Can this be replaced with a call to `getDatasetUids`?
Maybe we should take care of this while we are cleaning house?

2022-02-03 14:21 UTC, jason-p-pickering commented on R/createKeychainInfo.R
> +  d$info$source_user <- switch(!is.null(d2_session),
This might be safer? 

`any(class(d2_default_session) %in% "d2Session")`

2022-02-03 14:21 UTC, jason-p-pickering commented on R/createKeychainInfo.R
> +  d$info$organisation_unit <- getOUFromCountryUIDs(d$info$country_uids)
See my comment above.

2022-02-03 14:28 UTC, jason-p-pickering requested changes
Left a few comments.

2022-02-04 16:51 UTC, cnemarich commented on DESCRIPTION
> +    waldo,
Turns out that `validateSchema` isn't called anywhere in our package, including the `data-raw` files, and also isn't called in the app, so I think this is fine to leave as suggested for now.

2022-02-04 17:24 UTC, cnemarich commented on R/checkMechanisms.R
> +    d$info$had_error <- TRUE
```suggestion
    d$info$has_error <- TRUE
```

2022-02-04 17:40 UTC, cnemarich commented on R/createKeychainInfo.R
> +  d$info$source_user <- switch(!is.null(d2_session),
I just tried this in a fresh R session and got this error:
```
Error in class(d2_default_session) %in% "d2Session" : 
  object 'd2_default_session' not found
```

If we want to require being logged into DATIM for this function, I think that will work, but if the user isn't logged in I think this will create an error.

2022-02-04 19:39 UTC, cnemarich commented on R/checkPSNUData.R
> +  # TODO Can this be replaced with a call to `getDatasetUids`?
It actually looks like this `datasets_uid` object hasn't been needed since April of last year when it was removed from the `datimvalidation::validateData` function call:
https://github.com/pepfar-datim/datapackr-app/commit/00cee25526612db5dd6f74ed41d87050ab59fbe1#diff-60bef5af43a1bd541299ce9bceeb226afb23deaa5e637b145c85e05ffd552b0cL84

Maybe we can just remove lines 56-66 if it's not called anywhere anymore.

2022-02-04 20:09 UTC, cnemarich commented on R/checkPSNUData.R
> +                              paste0(Sys.getenv("support_files_directory"), "cop_validation_rules.rds"),
That seems like a good idea. We would just have to document it, which I'm not sure quite how to do with a nested object like that, and also change it to be saved as an `.rda` file.

2022-02-04 20:12 UTC, cnemarich commented on R/checkMechanisms.R
> +  operating_unit <- getOperatingUnitFromCountryUIDs(d$info$country_uids)
Yes, this wasn't edited when I moved that into the `createKeychainInfo` function. So this could be removed.

```suggestion

```

2022-02-04 20:13 UTC, cnemarich commented on R/checkMechanisms.R
> +    dplyr::filter(ou == operating_unit$ou) %>%
See comment above. This would reference metadata in `d` object.
```suggestion
    dplyr::filter(ou == d$info$operating_unit$ou) %>%
```

2022-02-04 20:14 UTC, cnemarich commented on R/createKeychainInfo.R
> +  d$info$organisation_unit <- getOUFromCountryUIDs(d$info$country_uids)
I think I've addressed your comment above with the suggested changes, but let me know if I misunderstood.

2022-03-03 19:07 UTC, JordanBalesBAO reviewed
Code reviewed and everything looks fine. Moving to functional testing.

2022-03-03 19:32 UTC, cnemarich commented on R/checkPSNUData.R
> +    if ("parallel" %in% rownames(installed.packages()) == TRUE) {
The `renv.lock` file would handle whether this package was installed in the first place, but can't handle whether to conditionally execute this code, which is why this is needed here.

2022-03-03 19:51 UTC, JordanBalesBAO approved these changes
Left more details on the Jira Ticket. Went through code changes with create detail, and tested front end functionality via the app. Looks good to me.

2022-03-03 20:12 UTC, flopez-bao approved these changes
Looked through the files and nothing stood out to me that looked out of place. I tested India and Indonesia 22 as well as Sudan without issue.

2022-03-04 16:14 UTC, merged