DP-663: Reduce cyclo complexity `validateSchema`
pepfar-datim/datapackr pull request #477
Opened 2022-05-25 18:32 UTC by cnemarich

## Developer:

### Summary of Proposed Changes
Reduces the cyclomatic complexity of the function `validateSchema` to lower than 15 to stop tripping linter.
* Combines all OPU tests under one if-then statement
* Reorders checks for `schema` and `template_path` to minimize `if-then` branching
* Removes `if-then` checks for failures on each test in favor of checking all tests at the end and removing any with zero rows
* Reduces overall cyclomatic complexity from 22 to 13

### Related Issues
- DP-663

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2022-05-26 05:21 UTC, jason-p-pickering requested changes
I think this is a good start, but I think we can do more to pull out some of the conditional code into separate small units which we can test.

2022-05-26 05:21 UTC, jason-p-pickering commented on R/unPackSchema.R
> +  if (schema_provided) {
My preference would be to move this to a small unit tested function instead. Can you move it out of the main function?

2022-05-26 05:21 UTC, jason-p-pickering commented on R/unPackSchema.R
> +    ## If template_path provided, check it and unpack it to create comparison schema.####
Same here. I think this can be moved to a small function instead.

2022-05-26 05:21 UTC, jason-p-pickering commented on R/unPackSchema.R
> +    if (schema_provided && !identical(schema, filepath_schema)) {
Same here. Another small function.

2022-05-27 14:58 UTC, cnemarich commented
Function names are too long and need to be shortened in a number of cases

2022-08-10 06:43 UTC, jason-p-pickering approved these changes

2022-08-10 06:44 UTC, jason-p-pickering commented
@JordanBalesBAO can you have a look at this PR? Both @cnemarich and I have worked on it, so better that we get someone else to review it.

2022-08-10 13:51 UTC, JordanBalesBAO commented
@jason-p-pickering Sure!

2022-08-10 17:11 UTC, JordanBalesBAO approved these changes
Looks good!

2022-08-15 10:26 UTC, merged