Dp 360
pepfar-datim/datapackr pull request #506
Opened 2022-06-02 17:33 UTC by cnemarich

## Developer:

### Summary of Proposed Changes

### Related Issues
- DP-360

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2022-06-03 09:03 UTC, jason-p-pickering commented on R/utilities.R
> -extractWorkbook <- function(d) {
Any reason this was deleted? Leading to test failures.

2022-06-03 17:59 UTC, cnemarich commented on R/unPackDataPack.R
> +  d$data <- within(d$data, rm("targets"))
Is there a particular reason why these `d$data` assignments were moved outside of the `separateDataSets` function so this process is no longer self-contained?

2022-06-09 07:12 UTC, jason-p-pickering commented on R/createKeychainInfo.R
> +  if (!tool_metadata$cop_year[1] %in% c(2018:2030)
Is there a specific reason that we do not use supported cop years here?

2022-06-12 20:34 UTC, jacksonsj commented on R/unPackDataPack.R
> +  d$data <- within(d$data, rm("targets"))
Yes. Before, the input was d and it was hardcoded to look for a certain dataframe under d$data. But the basic functionality is really a lot bigger: take data and separate it out by DATIM dataset (e.g., MER, SUBNAT, etc.). Making the data itself the input instead of d makes this function a lot more useful. But then if you're splitting one to many, the output has to be a list object. Hence...

2022-06-12 20:35 UTC, jacksonsj commented on R/utilities.R
> -extractWorkbook <- function(d) {
Replaced with loadDataPack. Tests now updated

2022-06-16 19:11 UTC, jacksonsj commented
From @jason-p-pickering:

Tried to load the Rwanda datapack and saw this in the console. Its not clear to me 1) Why we are getting this warning at all 2) Why we are getting it multiple times.
![image](https://user-images.githubusercontent.com/31488407/174147180-1c10171a-9792-437b-9bc0-f792db008339.png)

2022-06-16 19:12 UTC, jacksonsj commented
From @jason-p-pickering:

![image](https://user-images.githubusercontent.com/31488407/174147400-650be2d9-5d3e-40b2-a6e4-7630e0fc7a92.png)

from the Nigeria datapack

2022-06-16 19:13 UTC, jacksonsj commented
From @jason-p-pickering:

One other thing I have noticed, is that the test are running quite a bit slower. I think this is because each time we load a datapack in the tests, we run checkSheetData. I saw this comment, but not sure I agree with it:

```
  # Implementing this here instead of in unPackDataPack or unPackTool because
  # while you may want to checkSheetData without running unPackSheets, you should
  # should never unPackSheets without running checkSheetData
  d <- checkSheetData(d, sheets = sheets)
```

i think we should be able to skip the checks (since they take time and are tested elsewhere) during the CI run. So, if we added an additional parameter to loadDataPack and all dependent functions called check_sheet_data = TRUE (but set it to false in the unit tests), I think we should be able to safely skip those checks when loading from one of our test datapacks?

2022-06-16 19:13 UTC, jacksonsj commented
From @jason-p-pickering:

Next problem...performance

i checked against master with the Rwanda datapack...

14 seconds in master, and 28 seconds with DP-360

my impression previously was that this branch was faster, but now the parsing time appears to have doubled....

2022-06-30 17:46 UTC, jacksonsj commented
@jason-p-pickering - I'm really not sure where to go next on the performance issues you raised. This approach is definitely slower, I think because it requires loading and munging each sheet for each test performed, rather than before when tests were integrated in `unPackSheet` and so loading/munging happened just once upfront.

Options:
- If we alter the check functions to return a list of just `test_results` & `msg`, like in the `checkAnalytics` family, instead of the full `d` object, we could use `purrr::map` to run checks simultaneously. As is though, because each check alters `d` and then the next check uses that as input, we have to run each test for each sheet sequentially, which rules out `purrr::map`.
- Reverse course and reintegrate checks into `unPackSheet` as it was to begin with.
- Alter the checks further to allow them to be run against multiple `sheets` at once, rather than only against a single `sheet` at a time. For some checks, this would mean iterating over each sheet somehow and appending messages and results in a way that aligns with the new `messageQueue` approach. For other checks, you could potentially combine all data together from all sheets and check all at once, then split messages by a `sheet_name` column or something like that.

Thoughts?

2022-06-30 18:42 UTC, jason-p-pickering commented
Are any tests dependent on other tests?

2022-07-07 15:33 UTC, jacksonsj commented
@jason-p-pickering - Could you take a look at the new approach here, in `checkSheetData`? I've converted the underlying check functions to return a list of just test results, msg, lvl, & has_error, and then checkSheetData compiles these using map functions into d.

2022-08-02 10:25 UTC, jason-p-pickering requested changes
Looks good @jacksonsj.Could you reply to my questions? Otherwise, I think this is solid work.

2022-08-02 10:25 UTC, jason-p-pickering commented on tests/testthat/test-unPackingChecks.R
> +  expect_equal(nrow(d$tests$negative_values), 6L)
I was explicit about the number of rows which should be detected. Should we add this to all of the tests?

2022-08-02 13:43 UTC, jacksonsj commented on R/unPackingChecks.R
> +  # keep_cols <- d$info$schema %>%
Done

2022-08-02 13:44 UTC, jacksonsj commented on R/unPackSNUxIM.R
> +  # if (d$info$tool == "Data Pack") {
Removed.

2022-08-02 13:45 UTC, jacksonsj commented on R/unPackingChecks.R
> +    # TEST AGYW Tab for missing DSNUs ####
Need this one for future PR, but noted better in code.

2022-08-02 13:45 UTC, jacksonsj commented on R/unPackingChecks.R
> +    stop("Sorry! Can't check the PSNUxIM tab with this function.")
Will be once DP-472 is complete.

2022-08-02 13:47 UTC, jacksonsj commented on R/unPackingChecks.R
> +    d <- checkColumnStructure(d, sheet)
This code is outdated — was changed a week ago or so. This `for` loop isn't there anymore. Using this approach now:

```R
# Apply the list of check functions ----
  funs <- list(
    duplicate_rows = checkDupeRows,
    missing_cols = checkMissingCols,
    duplicate_columns = checkDupeCols,
    columns_out_of_order = checkOutOfOrderCols,
    non_numeric = checkNonNumeric,
    negative_values  = checkNegativeValues,
    decimal_values = checkDecimalValues,
    invalid_orgunits = checkInvalidOrgUnits,
    invalid_prioritizations = checkInvalidPrioritizations,
    altered_formulas = checkFormulas,
    defunct_disaggs = checkDisaggs
  )

  data_checks <-  purrr::map(funs, purrr::exec, sheets, d)

  d$tests <-
    append(d$tests,
           purrr::map(data_checks, ~ purrr::pluck(.x, "result"))) %>%
    purrr::discard(is.null)
```

2022-08-02 14:00 UTC, jacksonsj commented on tests/testthat/test-unPackingChecks.R
> +  expect_equal(nrow(d$tests$negative_values), 6L)
Done

2022-08-02 17:20 UTC, jacksonsj commented
Just a note that right now there is a warning in tests about missing parent prioritizations. Right now, the COP21 test sheet we use purposefully assigns a `29` as prioritization for one of the DSNUs — Berea. But `imputePrioritization` interprets this as a missing prioritization and flags as a warning. Also, this function checks for the list of expected prioritizations against the import file’s `orgUnit` column — if a PSNU gets left out for some reason across an entire Data Pack and ends up with no prioritization, `imputePrioritization` wouldn’t pick this up. I think we need to somehow better link `imputePrioritization` and `checkInvalidPrioritizations` (which detects missing and invalid prioritizations)

2022-08-02 17:29 UTC, merged