DP 768
pepfar-datim/datapackr pull request #537
Opened 2022-09-20 23:32 UTC by jacksonsj

## Developer: @jacksonsj 

### Summary of Proposed Changes

### Related Issues
- DP-768

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2022-09-20 23:40 UTC, jacksonsj commented
@jason-p-pickering - This has two failing tests that seem unrelated to anything changed in this PR. Seem to be issues in `dev` too maybe?

```
══ Failed tests ═══════════════════════════════════════════════════════���════════
── Error (test-get-code-list.R:6:5): We can get a list of PSNUs from DATIM ─────
Error in `UseMethod("status_code")`: no applicable method for 'status_code' applied to an object of class "try-error"
Backtrace:
    ▆
 1. └─datapackr::getDataPackOrgUnits(...) at test-get-code-list.R:6:4
 2.   └─datimutils::getMetadata(...)
 3.     └─datimutils:::api_get(...)
 4.       └─httr::status_code(resp)
── Failure (test-prepareMemoData.R:93:5): We can create Datapack memo data ─────
all(names(d$memo$datapack$by_prio[3:prio_cols_end]) %in% prioritization_dict()$name) is not TRUE

`actual`:   FALSE
`expected`: TRUE
```

The first has something to do with this line in `datimutils`: https://github.com/pepfar-datim/datimutils/blob/master/R/callDATIMapi.R#L100. Maybe this is related to the use of the `training` instance in our tests? Not sure.

The second one is because in one of our test sheets, we have some org units without prioritizations, leading to `NAs`, which don't have a match in `prioritization_dict()`.

If you are able to help resolve, that would be great.

2022-09-20 23:42 UTC, jacksonsj commented
@JordanBalesBAO - If you have a second, would love your eyes on this too, particularly around the datimutils test failure.

2022-09-21 16:51 UTC, JordanBalesBAO commented
@jacksonsj Spent some time looking at your branch. Not sure what is occurring datimutils wise. 

- I was able to manually run the org unit functions that are failing testing. 
- I used training.datim as well as datim
- The api responses new vs old look the exact same
- The only difference I found was the test should be failing with the names check as it leaves out the "lastUpdated" column
- My guess is the try-catch we added to datimutils a month back isn't playing nice with the mock_api packages

2022-09-21 18:01 UTC, JordanBalesBAO commented
Fausto and I took a second look together, and we both agree the api mock package might not be able to replicate the response code that the try catch tests for

2022-09-26 14:08 UTC, jason-p-pickering commented
@jacksonsj I updated the renv.lock file to use the latest version of datimutils, and I was able to at least execute the tests. At least they are failing now, but I think you should be able to proceed, either by fixing the code, or tests.

2022-10-03 13:34 UTC, jason-p-pickering commented
@jacksonsj I have fixed the unit tests as well as other problems in the memo preparation. 

I am a bit puzzled though about the valid_orgUnits object. I sort of thought the point of this PR was to fetch the organisation units from the server. But if that is the case, why do we still have this object in the package? I must be missing something....

2022-10-03 14:15 UTC, jason-p-pickering commented
Ah, right...I think the rest of this is in https://github.com/pepfar-datim/datapackr/pull/532. 

Honestly, I think it would be easier to continue here with @cnemarich work instead of trying to merge that branch. Do you agree  @jacksonsj ?

2022-10-18 00:02 UTC, jacksonsj commented
I'm looking at this now. Not ready to merge quite yet

2022-10-19 01:37 UTC, jacksonsj commented
@jason-p-pickering - One test still failing, related to `training` API snapshots of `organisationUnits`. Not sure how those were created or how to fix. Mind taking a quick look?

2022-10-19 06:09 UTC, jason-p-pickering commented on R/getPSNUs.R
> +  # Filter by country if needed ####
@jacksonsj I am not sure we want to do the filtering after the request. This means that when we are trying to get orgunits for Lesotho, we have to request them for Global, which is very expensive operation. Are you sure you want to do the filtering client side?

2022-10-19 15:58 UTC, jacksonsj commented on R/getPSNUs.R
> +  # Filter by country if needed ####
Filtering client side is, surprisingly, x times faster than filtering via API. If we could set up a SQL View, that would be x times faster even than that:

```
datimutils::loginToDATIM("~/.secrets/datim.json")
d2_session <- d2_default_session

country_uids <- c("qllxzIjjurr", #Lesotho,
                               "XtxUYCsDWrR", #Rwanda
                              "cDGPF739ZZr") #South Africa

api_filters <- "organisationUnitGroups.id:in:[AVy8gJXym2D,nwQbMeALRjL,mRRlkbZolDR]"
filters_with_country <- c(api_filters,
                                           paste0("ancestors.id:in:[",
                                                        paste(country_uids, collapse = ","),
                                                         "]"))

fields <-
    "id,name,lastUpdated,ancestors[id,name,organisationUnitGroups[id,name]],organisationUnitGroups[id,name]"

microbenchmark::microbenchmark(
  datimutils::getMetadata(
    "organisationUnits",
    api_filters,
    fields = fields,
    d2_session = d2_session),
  datimutils::getMetadata(
    "organisationUnits",
    filters_with_country,
    fields = fields,
    d2_session = d2_session),
  datimutils::getSqlView(sql_view_uid = "gsaaxFM8ZN0"),
  times = 5L,
  unit = "s")
  ```

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/31488407/196743576-8c3335f9-7e6a-4ad0-89eb-be53a8fe6f43.png">

2022-10-19 16:00 UTC, sam-bao commented on R/getPSNUs.R
> +  # Filter by country if needed ####
It is much faster to get psnus (and mil and dreams) using the getOrgUnitGroups endpoint

```
datimutils::getOrgUnitGroups("AVy8gJXym2D", 
fields = "organisationUnits[name,id]")
```

2022-10-19 17:11 UTC, jason-p-pickering requested changes
Please have look at my comments before merging @jacksonsj

2022-10-19 17:11 UTC, jason-p-pickering commented on R/adorn_import_file.R
> -getPriorizationSNU <- function(psnu_uids) {
Hmm...These get added back in #523 @jacksonsj

2022-10-19 17:11 UTC, jason-p-pickering commented on R/adorn_import_file.R
> -  assertthat::are_equal(NROW(psnu_import_file), row_num)
Is there a good reason we are commenting out this assertion?

2022-10-19 17:11 UTC, jason-p-pickering commented on R/adorn_import_file.R
> -  # TODO: Is this munging still required with the map being a function of fiscal year?
Remove this code if not needed.

2022-10-19 17:11 UTC, jason-p-pickering commented on R/createAnalytics.R
> +  if (d$info$unallocatedIMs || !d$info$has_psnuxim) {
Hmm...where did this come from?

2022-10-19 17:11 UTC, jason-p-pickering commented on renv.lock
> +      "Version": "0.6.0",
Noting the change to upgrade datimtutils here...

2022-10-19 17:56 UTC, jacksonsj commented on renv.lock
> +      "Version": "0.6.0",
This must've been added by Chris. Should I move it back to `0.5.1`?

2022-10-19 17:57 UTC, jacksonsj commented on R/createAnalytics.R
> +  if (d$info$unallocatedIMs || !d$info$has_psnuxim) {
This is in there twice and both came from something already in `dev`

2022-10-19 18:34 UTC, merged

2022-10-19 18:36 UTC, JordanBalesBAO commented
:+1::skin-tone-2: