DP 788: Generate Beta Packs
pepfar-datim/datapackr pull request #576
Opened 2022-11-29 22:19 UTC by jacksonsj

## Developer: @jacksonsj 

### Summary of Proposed Changes

### Related Issues
- DP-XXX
- etc.

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2022-11-29 22:22 UTC, jacksonsj commented
@jason-p-pickering - We'll need a follow up PR based on @christian-domaas's review of the output Data Packs, but wanted to get this PR started now since the original branch was related to Alpha Packs, not Beta Packs. I'll open a new branch focused on DP-713 for Beta Packs.

But this branch fills the need to be able to take model data and template and produce a first pass Data Pack for COP23

2022-11-30 07:54 UTC, jason-p-pickering requested changes

2022-11-30 07:54 UTC, jason-p-pickering commented on R/unPackSchema.R
> +  # params <- check_params(cop_year = cop_year %missing% NULL,
Remove this commented code if it is not needed

2022-11-30 07:54 UTC, jason-p-pickering commented on R/unPackSchema.R
> +    # if (cop_year == 2021) {
Remove commented code.

2022-11-30 07:54 UTC, jason-p-pickering commented on R/unPackSchema.R
> +  schema <- dplyr::bind_rows(skipped_schema, schema) %>%
Can be simplified. Remove final return statement here.

2022-11-30 07:54 UTC, jason-p-pickering commented on tests/testthat/test-GetDatasetUids.R
> +  #expect_identical(getDatasetUids(), getDatasetUids(getCurrentCOPYear()))
Test needs fixing.

2022-12-14 12:20 UTC, jason-p-pickering commented on data-raw/COP23/update_cop23_de_coc_co_map.R
> +schema <- datapackr::cop22_data_pack_schema
should this not be using the COP23 schema?

2023-01-20 06:46 UTC, jason-p-pickering commented on tests/testthat/test-unPackingChecks.R
> +      "Central Eastern Zone", "Central Eastern Zone [#SNU] [EGgIZbN4s1P]", "4", "4", "Sustained"
Double check that this needs to be changed

2023-01-24 19:19 UTC, merged