Dp 788 jpp
pepfar-datim/datapackr pull request #582
Opened 2023-01-11 16:26 UTC by jason-p-pickering

## Developer:

### Summary of Proposed Changes

### Related Issues
- DP-XXX
- etc.

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2023-01-18 20:24 UTC, jacksonsj requested changes

2023-01-18 20:24 UTC, jacksonsj commented on R/createKeychainInfo.R
> +unPackHomeTabMetadata <- function(submission_path)  {
Can we separate this into a separate PR and keep this one focused on the getValidOrgUnits change?

2023-01-18 20:24 UTC, jacksonsj commented on R/evaluateIndicators.R
> +  expr_regexes <- list(plus  = "\\+",
Can we separate this into a separate PR and keep this one focused on the getValidOrgUnits change?

2023-01-18 20:24 UTC, jacksonsj commented on R/fetchPrioritizationTable.R
> +  n_requests <- ceiling(nchar(paste(psnus, sep = "", collapse = ";")) / 2048)
Not sure I understand how this change fits in.

2023-01-18 20:24 UTC, jacksonsj commented on R/packDataPack.R
> +  # is packDataPack receiving a model path or a model structure?
Why the need to allow either path or file to be sent? Can we separate this into a separate PR and keep this one focused on the getValidOrgUnits change?

2023-01-18 20:24 UTC, jacksonsj commented on R/unPackSNUxIM.R
> +extractSNUxIMCombos <- function(d) {
This is a pretty significant reworking of this function. Can we separate this into a separate PR and keep this one focused on the getValidOrgUnits change?

2023-01-18 22:40 UTC, flopez-bao commented on R/packDataPack.R
> +  # is packDataPack receiving a model path or a model structure?
I think the purpose of this addition to packDataPack is from test coverage that was added [here](https://github.com/pepfar-datim/datapackr/blob/dev/tests/testthat/test-packDataPack.R). The purpose was to be able to feed in model data as shown [here](https://github.com/pepfar-datim/datapackr/blob/dev/tests/testthat/test-packTool.R#L17).  This adds transparency in the case of us seeing what exactly is model_data. This doesn't change anything in the logic other than to provide the option of passing an R object as opposed to a reading in an actual rds.

2023-01-19 05:16 UTC, jason-p-pickering commented on R/fetchPrioritizationTable.R
> +  n_requests <- ceiling(nchar(paste(psnus, sep = "", collapse = ";")) / 2048)
This is just a simplification. There was no need to pass the entire orgunit data frame to this function. All we need is a vector of PSNU UIDs.

2023-01-19 05:17 UTC, jason-p-pickering commented on R/packDataPack.R
> +  # is packDataPack receiving a model path or a model structure?
DP-788 was lacking some commits from both master and dev. I will make two separate pull requests for these, so that it becomes more obvious what has changed in this PR.

2023-01-19 05:18 UTC, jason-p-pickering commented on R/createKeychainInfo.R
> +unPackHomeTabMetadata <- function(submission_path)  {
I needed this again in `R/unPackCountryUIDs.R`

2023-01-19 14:15 UTC, flopez-bao approved these changes

2023-01-19 14:57 UTC, jason-p-pickering commented on R/evaluateIndicators.R
> +  expr_regexes <- list(plus  = "\\+",
I think this should be more clear once we merge with dev/master

2023-01-19 14:58 UTC, jason-p-pickering commented on R/unPackSNUxIM.R
> +extractSNUxIMCombos <- function(d) {
again, this was a diff from dev/master

2023-01-20 05:25 UTC, merged