Add test prepare model data
pepfar-datim/datapackr pull request #603
Opened 2023-02-02 18:00 UTC by flopez-bao

## Developer: Fausto

Test coverage for DP-871 adding a test for prepare_model_data.PSNUxIM.R.

### Related Issues
- DP-871

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2023-02-02 18:31 UTC, flopez-bao commented
@jason-p-pickering do you understand this type of failure on circleci? This passed linting and testing locally.

2023-02-06 18:43 UTC, flopez-bao commented
@jason-p-pickering what do you think of the test methodology now? I broke up the function into smaller pieces and attempted to test each piece individually. I think it's much clearer what each function is doing. I am unsure whether all this is necessary in this fashion, but I don't want to refactor so much of the function in a way that is very different from before in the middle of cop season.

2023-02-07 08:19 UTC, jason-p-pickering requested changes
I think this is a good improvement. I have suggested to remove some unneeded return statements, and perhaps to consider creating invidiual mocks to show the state of the data which enters each function. Overall though, I think its a very good improvement! Let me know what you think.

2023-02-07 08:19 UTC, jason-p-pickering commented on R/prepare_model_data.PSNUxIM.R
> +  return(res)
No need for this return statement. You can just pipe `res` directly out of the function.

2023-02-07 08:19 UTC, jason-p-pickering commented on R/prepare_model_data.PSNUxIM.R
> +  return(res)
Remove return

2023-02-07 08:19 UTC, jason-p-pickering commented on R/prepare_model_data.PSNUxIM.R
> +  return(res)
remove return

2023-02-07 08:19 UTC, jason-p-pickering commented on R/prepare_model_data.PSNUxIM.R
> +  return(res)
remove return

2023-02-07 08:19 UTC, jason-p-pickering commented on R/prepare_model_data.PSNUxIM.R
> +  return(res)
ditto

2023-02-07 08:19 UTC, jason-p-pickering commented on R/prepare_model_data.PSNUxIM.R
> +  return(res)
same here

2023-02-07 08:19 UTC, jason-p-pickering commented on R/prepare_model_data.PSNUxIM.R
> +    #TODO: Consider replacing with something more straightforward like is.list()
Remove or address this TODO

2023-02-07 08:19 UTC, jason-p-pickering commented on R/prepare_model_data.PSNUxIM.R
> +  # snuxim_model_data %<>%
Remove commented code.

2023-02-07 08:19 UTC, jason-p-pickering commented on tests/testthat/test-prepare_model_data.PSNUxIM.R
> +# library(datapackr)
Remove commented code

2023-02-07 08:19 UTC, jason-p-pickering commented on tests/testthat/test-prepare_model_data.PSNUxIM.R
> +    dplyr::slice(1:3, )
Not clear why this slice is needed?  Another approach would be to create a mock dataset

2023-02-07 08:19 UTC, jason-p-pickering commented on tests/testthat/test-prepare_model_data.PSNUxIM.R
> +    .addDedupeCols(.)
We lose a bit of the intent here, since what comes out of the pipe is not totally clear. Should consider to perhaps replace with a mock.

2023-02-07 08:19 UTC, jason-p-pickering commented on tests/testthat/test-prepare_model_data.PSNUxIM.R
> +    res$`Custom DSD Dedupe Allocation (FY22) (% of DataPackTarget)`,
Are these FY22 hardcoded?

2023-02-07 15:29 UTC, flopez-bao commented on tests/testthat/test-prepare_model_data.PSNUxIM.R
> +    .addDedupeCols(.)
i think this is fine because a user can just run this snippet and produce the input then print the input and quickly see what is going into the test. That's why i separated this from res.

2023-02-07 15:33 UTC, flopez-bao commented on tests/testthat/test-prepare_model_data.PSNUxIM.R
> +    res$`Custom DSD Dedupe Allocation (FY22) (% of DataPackTarget)`,
yeah so the columns are named[ like this](https://github.com/pepfar-datim/datapackr/blob/dev/R/prepare_model_data.PSNUxIM.R#L141) which seems like an issue to me. Do you think as part of this ticket we change that hard coding?

2023-04-13 11:05 UTC, jason-p-pickering commented on R/prepare_model_data.PSNUxIM.R
> +  return(res)
OK, but now you do not return anything from the function? Is this intentional?

2023-04-13 13:59 UTC, flopez-bao commented on R/prepare_model_data.PSNUxIM.R
> +  return(res)
There is no need to return anything, line 10   `res <- res %>%` declares that res is the result of the pipe. I can change it to `res %<>%` but I don't think that necessarily a better programmatic practice.

2023-04-25 16:16 UTC, merged