Release 6.3.2
pepfar-datim/datapackr pull request #698
Opened 2023-05-18 23:57 UTC by JordanBalesBAO

## Developer: Team

Release Branch Review

2023-05-18 23:59 UTC, JordanBalesBAO commented
If we want the other 2 pull requests related to: 

- Tests
- CompareOPU 

Then we need to point them here **BEFORE** spending time reviewing this. Im okay pushing them to the next release, but I will heed to the developers who spent time coding them.

2023-05-19 00:04 UTC, JordanBalesBAO commented
I will need some help on the news.md

2023-05-19 14:33 UTC, JordanBalesBAO commented
Ready for review

2023-05-22 12:18 UTC, jason-p-pickering commented on R/unPackSNUxIM.R
> +    dplyr::filter(value > 0)
@JordanBalesBAO @flopez-bao @jacksonsj I am not sure we want to filter out values greater than zero here. Are we sure that we will get zero valued dedupes?

2023-05-22 12:20 UTC, jason-p-pickering requested changes
I think we need to review the line that filters values greater than zero....

2023-06-22 19:30 UTC, JordanBalesBAO reviewed
Completed my second round of code review

2023-06-22 20:27 UTC, flopez-bao reviewed
Aside from the zero filter comment, looked through the code and ran a few 23 datapacks through. Only thing to flag is since this includes the dev branch, it flags invalid org units as errors for the row in most of the datapacks that has an NA value, same conversation in [pr-695](https://github.com/pepfar-datim/datapackr/pull/695). 

Don't think this is a problem, I mention it because that's really the only thing holding up PR-695, so if we can agree on that, we can merge 695 into this release and should be good to go.

2023-06-22 21:31 UTC, JordanBalesBAO commented
Lets discuss at standup in the morning and get 695 merged if so

2023-06-23 13:36 UTC, jacksonsj commented on R/unPackSNUxIM.R
> +    dplyr::filter(value > 0)
Looks like this change was committed by @jason-p-pickering on April 26 here: https://github.com/pepfar-datim/datapackr/commit/bd5bad5693c0cc7b9f5a1e61e2d5935312f7a660, and then reverted as part of this PR, yes?

2023-06-23 13:49 UTC, jacksonsj commented on R/unPackSNUxIM.R
> +    dplyr::filter(value > 0)
Tracking this issue here: https://jira.pepfar.net/browse/DP-1112

I vote we address in a follow-on PR and move this release forward.

2023-06-23 17:49 UTC, JordanBalesBAO commented
> conversation

Issue being tracked here,

https://jira.pepfar.net/browse/DP-1113

2023-06-23 17:51 UTC, JordanBalesBAO commented
The two stated "issues" have been captured in tickets. 

1. In regards to the non zero's this hot fix was backed out a long time ago, and this Release branch should reflect such
2. In regards to the blank row, based upon conversation between Fausto, Jason, and I this is how we want the software to perform. 

@jason-p-pickering  keep us honest, is this a good justification?

2023-06-26 15:54 UTC, jason-p-pickering commented on R/unPackSNUxIM.R
> +    dplyr::filter(value > 0)
I have an entire branch that started out addressing this, but has since morphed into something bigger. I agree we should track this issue in another ticket.

2023-06-26 15:56 UTC, jason-p-pickering commented
> 2. In regards to the blank row, based upon conversation between Fausto, Jason, and I this is how we want the software to perform.
> 
> @jason-p-pickering keep us honest, is this a good justification?

I see no good justification to not identify those rows in empty sheets as an error. I think whatever we do though, how we want the software to perform should be captured in a unit test. This is not the case currently for this particular issue, so I agree that for now, we should maybe just ignore it and deal with it more comprehensively in the next release.

2023-06-27 13:02 UTC, jason-p-pickering approved these changes

2023-06-27 13:09 UTC, merged