DP-1071, DP-1110, DP-1088
pepfar-datim/datapackr pull request #703
Opened 2023-06-15 14:03 UTC by jacksonsj

## Developer:

### Summary of Proposed Changes

### Related Issues
- DP-XXX
- etc.

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2023-06-20 14:18 UTC, jason-p-pickering commented on R/packTool.R
> +  d <- suppressWarnings(
Do we really want to suppress the warnings?

2023-06-20 14:24 UTC, jacksonsj commented
That column width issue seems to be coming from these two pieces of code:

https://github.com/pepfar-datim/datapackr/blob/DP-1071/R/packPSNUxIM.R#L653-L657
https://github.com/pepfar-datim/datapackr/blob/DP-1071/R/packPSNUxIM.R#L667-L670

If I comment these out, file writes just fine.

2023-06-27 16:56 UTC, jacksonsj commented
@jason-p-pickering - Ready for your review

2023-06-28 04:52 UTC, jason-p-pickering requested changes
In general, I think it looks good. Have requested a few changes. I will put together a unit test in a separate branch.

2023-06-28 04:52 UTC, jason-p-pickering commented on R/packPSNUxIM.R
> +  years.in.play <- c("PSNUxIM", "OPU Data Pack") %>%
Please use snake case for variable names.

2023-06-28 04:52 UTC, jason-p-pickering commented on R/packPSNUxIM.R
> +  # openxlsx::setColWidths(wb = r$wb,
All of this seems very odd to me, but it looks like you found a solution. Can you remove the commented code? Not sure we need it if we found something which works.

2023-06-28 23:40 UTC, jacksonsj commented on R/packPSNUxIM.R
> +  # openxlsx::setColWidths(wb = r$wb,
Stashing here for future reference:
```
# openxlsx::setColWidths(wb = r$wb,
  #                        sheet = "PSNUxIM",
  #                        cols = col.im.percents[1]:col.im.percents[2],
  #                        widths = 10)
  # 6/27/23 SJJ - For some reason the above throws this error, while
  # removeColWidths does not:
  #
  # Error in sprintf("<col min=\"%s\" max=\"%s\" width=\"%s\" hidden=\"%s\" customWidth=\"1\"/>", :
  # arguments cannot be recycled to the same length
```

2023-06-28 23:45 UTC, jacksonsj commented
@jason-p-pickering - I think I've addressed everything. Mind taking another look?

2023-06-29 08:35 UTC, jason-p-pickering approved these changes
Looks good to me. Just maybe check that one comment about the default arg

2023-06-29 08:35 UTC, jason-p-pickering commented on R/createDataPack.R
> +                           season,
No need to set a default argument value (NULL) here?

2023-07-13 20:18 UTC, JordanBalesBAO commented
So are we good to get this into dev? If so I will cut for the release.

2023-07-14 13:50 UTC, jacksonsj commented on R/createDataPack.R
> +                           season,
Because this function uses `check_params` at the top, and includes `season`, we don't need `NULL` default arg, because even an empty arg will get filtered and replaced with whatever the package default is, defined in `check_params`.

2023-07-14 13:50 UTC, merged