Removes a filter that was blocking "dreams" data from making its way …
pepfar-datim/datapackr pull request #723
Opened 2023-08-02 14:03 UTC by JordanBalesBAO

…through the compare function

## Developer: JBales

### Summary of Proposed Changes
Removes a filter that was blocking "dreams" data from making its way through the compare function

### Related Issues
- DP-1129

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2023-08-02 15:09 UTC, flopez-bao approved these changes

2023-08-03 07:28 UTC, jason-p-pickering requested changes

2023-08-03 07:28 UTC, jason-p-pickering commented on R/datapackVsDatim.R
> -      dplyr::filter(dataset %in% datastreams)
@JordanBalesBAO I think I am OK with this, but maybe we are going too far? If you look at the function definition, one could also change the default parameters (or supply them) to include the `dreams` dataset, which I think would have the effect of including the DREAMS data. Maybe this is the better approach as opposed to removing this line of code? Otherwise, the `datastreams` parameter seems to have no effect. I am just not sure if there may be unintended side effects with pursuing this route?

2023-08-03 13:38 UTC, JordanBalesBAO commented on R/datapackVsDatim.R
> -      dplyr::filter(dataset %in% datastreams)
I agree with your logic completely. So that was actually the first path I went down,  added 'dreams' to the datastream list then added on line 91 dataset == dreams ~ dreams. The wall I hit came down stream at 152-160 where getCOPDataFromDATIM() runs twice.  Any guidance, or do I just need to keep tinkering?

2023-08-03 16:43 UTC, JordanBalesBAO commented
Should be good to re-review.

2023-08-04 06:19 UTC, jason-p-pickering approved these changes

2023-08-04 11:51 UTC, merged