Update COP24 Validation Rules
pepfar-datim/datapackr pull request #770
Opened 2023-12-19 14:31 UTC by flopez-bao

## Developer: Fausto

### Summary of Proposed Changes
- update cop24 validation rules
- add code for direct download of rules
- add code for handling column changes

### Related Issues
- DP-1063

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2024-01-09 14:23 UTC, jason-p-pickering requested changes

2024-01-09 14:23 UTC, jason-p-pickering commented on data-raw/cop_validation_rules.R
> +# DEPRECATE 21 and 22 as of 12/19/23
Remove this commented code.

2024-01-09 14:23 UTC, jason-p-pickering commented on tests/testthat/test-checkPSNUData.R
> +    d$info$cop_year <- "2023"
Do we need a test here for COP24?

2024-01-09 14:23 UTC, jason-p-pickering commented on data-raw/cop_validation_rules.R
> +url <- paste0(base_url, "api/validationRules.json?",
It might be easier to use URLDecode to get the actual URL

2024-01-09 15:03 UTC, flopez-bao commented
@jason-p-pickering added tests and removed commented code. Not sure about how to use urlDecode in an advantageous way.

2024-01-11 20:57 UTC, JordanBalesBAO approved these changes

2024-01-11 20:59 UTC, merged