Dp 1186
pepfar-datim/datapackr pull request #772
Opened 2024-01-09 22:13 UTC by JordanBalesBAO

## Developer:

### Summary of Proposed Changes

### Related Issues
- DP-XXX
- etc.

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2024-01-10 08:13 UTC, jason-p-pickering commented on R/writePSNUxIM.R
> +                                        d$info$cop_year %% 100,
huh?

2024-01-10 08:14 UTC, jason-p-pickering commented on R/writePSNUxIM.R
>                     "2022" = "OPU Data Pack",
should be removed i think?

2024-01-10 08:14 UTC, jason-p-pickering commented on R/writePSNUxIM.R
> +    schema <- if (d$info$cop_year == 2023) {
I think we do have a pickSchema function?

2024-01-10 08:15 UTC, jason-p-pickering requested changes
Few small issues which I think can be improved upon

2024-01-11 21:00 UTC, closed without merging

2024-01-11 21:42 UTC, JordanBalesBAO commented on R/writePSNUxIM.R
> +                                        d$info$cop_year %% 100,
grabs the last two digits of cop year. Ex 2024 will be 24