added test for strip_wb_nas
pepfar-datim/datapackr pull request #842
Opened 2024-05-31 16:20 UTC by flopez-bao

### Summary of Proposed Changes
- added test for strip_wb_nas
- some in line documentation for the function

### Related Issues
- DP-873

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2024-06-04 04:22 UTC, jason-p-pickering requested changes

2024-06-04 04:22 UTC, jason-p-pickering commented on R/strip_wb_NAs.R
>    NA_sharedString <- grep("<si><t>NA</t></si>", d$tool$wb$sharedStrings) - 1
Is it maybe better to use grepl here since we are just looking for the presence of these strings?

2024-06-04 04:22 UTC, jason-p-pickering commented on R/strip_wb_NAs.R
> +      # identify cells with sharedStrings that might be "NA"
I think it could be simpler to make this code inside a function and then write the unit test on that (outside of the loop)?

2024-06-04 17:56 UTC, flopez-bao commented
@jason-p-pickering responding to your 2 comments - 

comment 1. seems to me the indices is what the function is looking for hence the grep. I can see in the [original code](https://github.com/pepfar-datim/datapackr/commit/9415fc2edffee9e0bd70cdec196cbb464810ae35) this was done as a response to the [647](https://github.com/pepfar-datim/Data-Pack/issues/647#issuecomment-587360871). Best not to change unless you have a specific solution in mind.

comment 2. i moved that portion into a function `process_sheet` declared inside `strip_wb_NAs`, not sure if that's what you meant, but does look cleaner and did lapply instead of for loop.

2024-06-05 05:35 UTC, jason-p-pickering commented
Yes I see now what you mean on closer inspection of the code. Looks good to me now.

2024-06-06 12:03 UTC, JordanBalesBAO approved these changes

2024-06-06 12:03 UTC, JordanBalesBAO approved these changes

2024-06-06 12:04 UTC, merged