Tsnu changes 1
pepfar-datim/datapackr pull request #879
Opened 2024-11-15 19:14 UTC by JordanBalesBAO

## Developer:

### Summary of Proposed Changes

### Related Issues
- DP-XXX
- etc.

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

2024-11-21 17:08 UTC, jason-p-pickering requested changes
I think this needs a bit more work. Check the upper case variable names and be sure we want to go this route. Typically we have used snake_case. The liberal use of > as opposed to %in% makes me a bit nervous long term.

2024-11-21 17:08 UTC, jason-p-pickering commented on R/packSheets.R
> +      if (cop_year > 2024) {
I am not sure we want > here? This might lead to problems down the road.

2024-11-21 17:08 UTC, jason-p-pickering commented on R/packSheets.R
> +        dplyr::filter(!is.na(HISTORIC_PSNU)) %>%
Is there a need to use CAPITAL_LETTERS here?

2024-11-21 17:08 UTC, jason-p-pickering commented on R/packSheets.R
> +          dplyr::filter(!is.na(DREAMS)) %>%
I am not sure we should be using CAPS again here?

2024-11-21 17:08 UTC, jason-p-pickering commented on data-raw/COP25/COP25_Data_Pack_generation_script.R
> +  Sys.getenv("SECRETS_FOLDER") %>% paste0(., "coptest.json")
Likely this should also be an environment variable

2024-11-21 17:08 UTC, jason-p-pickering commented on tests/testthat/test-getValidOrgUnits.R
> +    all_cop_years <- supportedCOPYears()[supportedCOPYears() < 2025]
Again, not entirely sure we want to use < as opposed to %in% here in order to be explicit.

2024-11-21 17:08 UTC, jason-p-pickering commented on tests/testthat/test-generateCOP25DataPack.R
> +    # Malwi requires TSNUS which for Malawi are country level for other sheets
Typo here.

2024-11-21 17:08 UTC, jason-p-pickering commented on R/packSheets.R
I find the changes here hard to follow, particular the introduction of the concept of "historical" PSNUs

2024-11-22 13:32 UTC, flopez-bao commented on data-raw/COP25/COP25_Data_Pack_generation_script.R
> +  Sys.getenv("SECRETS_FOLDER") %>% paste0(., "coptest.json")
Already was there, believe Nemarich added it back in the day for the generation scrips. We use this process in order to swap jsons when using different servers.

2024-11-22 13:42 UTC, flopez-bao commented on R/packSheets.R
> +      if (cop_year > 2024) {
changed to %in%

2024-11-22 13:42 UTC, flopez-bao commented on R/packSheets.R
> +          dplyr::filter(!is.na(DREAMS)) %>%
was already capitalized so leaving for now

2024-11-22 13:42 UTC, flopez-bao commented on tests/testthat/test-getValidOrgUnits.R
> +    all_cop_years <- supportedCOPYears()[supportedCOPYears() < 2025]
changed to %in%

2024-11-22 13:42 UTC, flopez-bao commented on tests/testthat/test-generateCOP25DataPack.R
> +    # Malwi requires TSNUS which for Malawi are country level for other sheets
fixed

2024-11-22 13:46 UTC, flopez-bao commented
- caps were dropped
- operators swapped for `%in%`
- changed `HISTORIC_PSNUS` to `country_was_psnu` flag for a more intuitive name, the flag is similar to way we handle DREAMS for AGYW tab, it marks countries that were historically psnus at the national level like Colombia so we can display it differently in Prioritization

2024-11-22 19:22 UTC, jason-p-pickering approved these changes

2024-11-22 19:22 UTC, jason-p-pickering commented
Please fix the conflicts before merging, but that should be straightforward

2024-11-22 19:56 UTC, merged